### ISSUE TITLE
Github Installation ERROR: Command errored out with exit status 1

### ISSUE THREAD

**Issue by gsalfourn** [hellohaptik/spello#20]
In response to `https://github.com/hellohaptik/spello/issues/19` you suggested that "if it is possible you can build and install from a master directly which has the fix" and you provided the installation script below:

```
git clone https://github.com/hellohaptik/spello/
cd spello
pip install .
```

I adapted the script you provided, and used the scripts below:

```
D:\Python\bertopic\topicsmodels>.\topicmodelsENV\Scripts\activate

(topicmodelsENV) D:\Python\bertopic\topicsmodels>py -m pip install git+https://github.com/hellohaptik/spello/
````

which run up to a point:

```
Collecting git+https://github.com/hellohaptik/spello/
  Cloning https://github.com/hellohaptik/spello/ to c:\users\<username>\appdata\local\temp\pip-req-build-yukbnv4f
  Running command git clone -q https://github.com/hellohaptik/spello/ 'C:\Users\<username>\AppData\Local\Temp\pip-req-build-yukbnv4f'
  Resolved https://github.com/hellohaptik/spello/ to commit a9423a91a6eb1423702d3e7f2d5726ba99d9904d
```
before erroring out:
```
    ERROR: Command errored out with exit status 1:
     command: 'D:\Python\bertopic\topicsmodels\topicmodelsENV\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\<username>\\AppData\\Local\\Temp\\pip-req-build-yukbnv4f\\setup.py'"'"'; __file__='"'"'C:\\Users\\<username>\\AppData\\Local\\Temp\\pip-req-build-yukbnv4f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\<username>\AppData\Local\Temp\pip-pip-egg-info-22a3wgy0'
         cwd: C:\Users\<username>\AppData\Local\Temp\pip-req-build-yukbnv4f\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\<username>\AppData\Local\Temp\pip-req-build-yukbnv4f\setup.py", line 4, in <module>
        long_description = fh.read()
      File "C:\Python39\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 1494: character maps to <undefined>
    ----------------------------------------
WARNING: Discarding git+https://github.com/hellohaptik/spello/. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by chiragjn** [comment]
Thanks for reporting this. Seems like this is a pretty common mistake with packaging code and we didn't test our code on windows machines. I just made a fix commit on the `master` branch for this.
Let me know if the following works,

```
cd  spello/ # wherever you cloned
git pull origin master
pip install .
```
