### ISSUE TITLE
error: missing ), unterminated subpattern

### ISSUE THREAD

**Issue by shantanuo** [hellohaptik/spello#5]
```
from spello.model import SpellCorrectionModel

sp = SpellCorrectionModel(language="en")
sp.load("en_large.pkl")

text = "Got the phone delivered on time . That is the only good thing in this entire experience of mine . (Updated now) a new update , the first update didn' t provide any noticeable difference but this one's log looks promising, let's see. . I have been using various models of mobiles , have never seen such a terrible device , . Bought this after much thoughts by trusting the name Lenevo . I have been using redmi note 4 & it never had any issues with battery or even camera . Listening to music through YouTube , Browsing, Facebook , Insta , still solid backup for more than a dayI have 4 other phones also , MO TO G3 & Samsung S3 , H TC 62 8G , Samsung J7 Prime . This phone(L enevo K 8) seems to be worst among all. 1) Battery : Has left me shattered with its worst battery life , Have just used to take some pictures , YouTube & songs , it goes down very Fast . (Yet to enter two sim card & use What sApp , Gmail , so if it continues to become more worst I'd surely update & escalate this )2  , Camera Quality (For a dual camera , it is nowhere near Honor 6x which is 1k lesser) . if you are tricked by the dual camera ( it still has not got update of slowmo , Time lapse ) but it is really good when taken in Professional Mode with manual iso & focussing. A disaster in auto mode , that too for a rear camera with dual lens . I wish the company wakes up and starts rolling out O TA update for Camera & Battery life improvement. Other than that , The phone is super smooth , Display , Touch , Finger print sensor & stock Android is a bit of self satisfaction that I can say to myself for wasting 1 4K . I thought of gifting it to my father , but this would make it surely an incomplete gift . !Wish the company looks into these issues & provides updates for the Camera & Battery life because that is what it was paid for & marketed by the company claiming those 2 are the highlight factors. Lost interest to Even post pictures of it. With much regret."


sp.spell_correct(text)["spell_corrected_text"]


---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
<ipython-input-4-5649933b90e6> in <module>
----> 1 sp.spell_correct(text)["spell_corrected_text"]

/opt/conda/lib/python3.7/site-packages/spello/model.py in spell_correct(self, text, verbose)
    254             logger.debug(f"Suggestions dict from phoneme and symspell are: {suggestions_dict}")
    255 
--> 256             context_corrected_text, context_corrections = self.context_suggestion(clean_text, suggestions_dict)
    257 
    258             logger.debug(f"text after context model: {context_corrected_text}")

/opt/conda/lib/python3.7/site-packages/spello/model.py in context_suggestion(self, text, suggestions_dict)
    114             suggestions_dict = {key: value[0] for key, value in suggestions_dict.items()}
    115             return text, suggestions_dict
--> 116         text, context_corrections = self.context_model.context_spell_correct(text, suggestions_dict)
    117         return text, context_corrections
    118 

/opt/conda/lib/python3.7/site-packages/spello/context/context.py in context_spell_correct(self, sentence, suggestions_dict)
    190         context_corrected_sentence = " " + sentence + " "
    191         for token, suggestion in corrected_dict.items():
--> 192             context_corrected_sentence = re.sub(" " + token + " ", " " + suggestion + " ", context_corrected_sentence)
    193         context_corrected_sentence = context_corrected_sentence.strip()
    194         return context_corrected_sentence, corrected_dict

/opt/conda/lib/python3.7/re.py in sub(pattern, repl, string, count, flags)
    190     a callable, it's passed the Match object and must return
    191     a replacement string to be used."""
--> 192     return _compile(pattern, flags).sub(repl, string, count)
    193 
    194 def subn(pattern, repl, string, count=0, flags=0):

/opt/conda/lib/python3.7/re.py in _compile(pattern, flags)
    284     if not sre_compile.isstring(pattern):
    285         raise TypeError("first argument must be string or compiled pattern")
--> 286     p = sre_compile.compile(pattern, flags)
    287     if not (flags & DEBUG):
    288         if len(_cache) >= _MAXCACHE:

/opt/conda/lib/python3.7/sre_compile.py in compile(p, flags)
    762     if isstring(p):
    763         pattern = p
--> 764         p = sre_parse.parse(p, flags)
    765     else:
    766         pattern = None

/opt/conda/lib/python3.7/sre_parse.py in parse(str, flags, pattern)
    928 
    929     try:
--> 930         p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
    931     except Verbose:
    932         # the VERBOSE flag was switched on inside the pattern.  to be

/opt/conda/lib/python3.7/sre_parse.py in _parse_sub(source, state, verbose, nested)
    424     while True:
    425         itemsappend(_parse(source, state, verbose, nested + 1,
--> 426                            not nested and not items))
    427         if not sourcematch("|"):
    428             break

/opt/conda/lib/python3.7/sre_parse.py in _parse(source, state, verbose, nested, first)
    817             if not source.match(")"):
    818                 raise source.error("missing ), unterminated subpattern",
--> 819                                    source.tell() - start)
    820             if group is not None:
    821                 state.closegroup(group, p)

error: missing ), unterminated subpattern at position 6
```

**Comment by amansrivastava17** [comment]
@shantanuo the issue has been fixed, you can pull master branch. Will be releasing the new pip version with major bug fixes soon

**Comment by rituraj123db** [comment]
ERROR: Unrecoverable exception thrown when parsing ./manage.py! This should NEVER happen.
If encountered, please open an issue: https://github.com/PyCQA/isort/issues/new
Traceback (most recent call last):
  File "/home/ideal48/Projects/property_service/venv/bin/isort", line 8, in <module>
    sys.exit(main())
  File "/home/ideal48/Projects/property_service/venv/lib/python3.8/site-packages/isort/main.py", line 953, in main
    for sort_attempt in attempt_iterator:
  File "/home/ideal48/Projects/property_service/venv/lib/python3.8/site-packages/isort/main.py", line 939, in <genexpr>
    sort_imports(  # type: ignore
  File "/home/ideal48/Projects/property_service/venv/lib/python3.8/site-packages/isort/main.py", line 95, in sort_imports
    incorrectly_sorted = not api.sort_file(
  File "/home/ideal48/Projects/property_service/venv/lib/python3.8/site-packages/isort/api.py", line 324, in sort_file
    changed = sort_stream(
  File "/home/ideal48/Projects/property_service/venv/lib/python3.8/site-packages/isort/api.py", line 158, in sort_stream
    changed = core.process(
  File "/home/ideal48/Projects/property_service/venv/lib/python3.8/site-packages/isort/core.py", line 332, in process
    parsed_content = parse.file_contents(import_section, config=config)
  File "/home/ideal48/Projects/property_service/venv/lib/python3.8/site-packages/isort/parse.py", line 513, in file_contents
    placed_module = finder(module)
  File "/home/ideal48/Projects/property_service/venv/lib/python3.8/site-packages/isort/place.py", line 17, in module
    return module_with_reason(name, config)[0]
  File "/home/ideal48/Projects/property_service/venv/lib/python3.8/site-packages/isort/place.py", line 26, in module_with_reason
    or _known_pattern(name, config)
  File "/home/ideal48/Projects/property_service/venv/lib/python3.8/site-packages/isort/place.py", line 56, in _known_pattern
    for pattern, placement in config.known_patterns:
  File "/home/ideal48/Projects/property_service/venv/lib/python3.8/site-packages/isort/settings.py", line 555, in known_patterns
    self._known_patterns.append((re.compile(regexp), placement))
  File "/usr/lib/python3.8/re.py", line 252, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.8/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.8/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.8/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.8/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.8/sre_parse.py", line 836, in _parse
    raise source.error("missing ), unterminated subpattern",
re.error: missing ), unterminated subpattern at position 1
